### ISSUE TITLE
Magento 2.4.8 / Office 365

### ISSUE THREAD

**Issue by ShapesGraphicStudio** [magepal/magento2-gmail-smtp-app#196]
Hello,
Just updated to 3.0.0 module now tries to send the mail.
But I'm facing a new issue with Office 365 config (working fine with Magento 2.4.7-p5 and SMTP module v2.9.2).

Test mail is returning following error:

Connection could not be established with host "ssl://smtp.office365.com:587": stream_socket_client(): SSL operation failed with code 1. OpenSSL Error messages: error:1408F10B:SSL routines:ssl3_get_record:wrong version number

SSL Type is TLS
SMTP Host is smtp.office365.com
SMTP Port is 587

I'm also facing some admin page loading js issues as on some page loads the config fields are not showing up.. I have to hard refresh the page to make the input fields show up again. No issue when the module is disabled.

Some errors showing in console:
Uncaught TypeError: b.tagName is undefined
Uncaught TypeError: $(...).filter(...).collapse is not a function
Uncaught TypeError: ah.dispatchEvent is not a function

On hard refresh these errors occur no more and I can edit config.

Any ideas please?

**Comment by wssweb** [comment]
switch to SSL type auth on port 465

**Comment by cla01-bit** [comment]
@danielkarso-pon awesome, it works now using STARTTLS thank you! May i ask when we can except a new release that includes the fix?
